# Developed by Eng. Mouaz M. Al-Shahmeh
name: currency_converter_flutter_app
description: Developed by Eng. Mouaz M. Al-Shahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  substring_highlight: ^1.0.33
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/flags/
    - assets/data/
